### ISSUE TITLE
The Info modal needs a close button

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#1]
The info modal can currently be closed by tapping outside of the modal or pressing the `Esc` key.

While this is fine, it is a little unclear, and on mobile it can be tricky to tap outside of the modal.

We need to change line 74 in App.js (in the src folder) **from** `<Modal.Header>` **to** `<Modal.Header closeButton>`

**Comment by jenovs** [comment]
Can't we just add `closeButton` attribute to `Modal.Header`?

**Comment by JacksonBates** [comment]
Maybe - I didn't read the docs to closely :)

Do you fancy giving it a try? If it turns out to be that easy, we can modify the similar issue #2 and make it an easy first-timer gig.

**Comment by jenovs** [comment]
Works like a charm:

![close](https://cloud.githubusercontent.com/assets/10571704/20686527/c5e25b42-b5c1-11e6-9558-1e18ddfae146.png)

**Comment by JacksonBates** [comment]
Cool - you wanna make the pull request?

**Comment by jenovs** [comment]
Ok.

**Comment by JacksonBates** [comment]
Oops, I just noticed you added it to the form modal, not info :)

Oh, well. I'll close issue #2 and add this process to #1 instead for first timers :)

**Comment by jenovs** [comment]
Ups :tired_face:

**Comment by JacksonBates** [comment]
@jenovs Code review is only as good as your code reviewer, eh ;)

**Comment by jer244** [comment]
I just submitted a PR for this issue.  Thanks @jenovs for doing the 'hard part'!
