### ISSUE TITLE
Handle the unhandled Promise rejection thrown by the App.test.js

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#23]
Currently, the only test we run is one that checks whether the app renders successfully.

You can do this by running `npm run test` at the terminal.

However, while the test passes, this warning is given:

> (node:7502) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Network request failed

This is likely because the backend only accepts requests from the pairboard.surge.sh domain, and the test is probable coming form localhost.

So the first issue to solve is to handle the promise rejection. We may also need to rethink how the tests communicate with the backend - I'd like to hear thoughts on that...

**Comment by jenovs** [comment]
There is missing `catch` statement after `fetch`. In node 7.0.0:

>Unhandled Promise rejections have been deprecated and will emit a process warning #8217.

It should be like this:
```
  componentWillMount() {
    fetch('https://enigmatic-dawn-95873.herokuapp.com/api/v1/posts')
      .then(result => result.json())
      .then(result => this.setState( { campers : result }))
      .catch(e => e);
  }
```

**Comment by JacksonBates** [comment]
Cool. Have you tested that?

**Comment by jenovs** [comment]
Yep. All one test case pases :smile:

**Comment by JacksonBates** [comment]
Awesome :) Feel free to PR

**Comment by jenovs** [comment]
It's 1am here. I'll leave it for tomorrow.

If someone wants to make PR, feel free to do it. If no takers I'll PR tomorrow.

PR created.
