### ISSUE TITLE
Improve language used to describe 'available time'

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#3]
It is not entirely clear what a user should write to in the form for 'available time'
![image](https://cloud.githubusercontent.com/assets/4337740/20661466/fc7b7c98-b5a2-11e6-840c-db7d752a1728.png)

The intention is that people write, in hours and minutes, how long they currently have available to them for pair programming. 

E.g. If a user has 3 hours, they should write `3:00`. (Or `03:00` ideally, but the backend is smart enough to know they are the same thing).

Please discuss your proposed language improvements below, and whoever gets assigned can make the appropriate change.

The form can be found on lines 49-72 in the Modal, in App.js in the src folder.

Changes may need to occur elsewhere - _please discuss first_.

Possible improvements include:
+ Clearer wording
+ Tool-tips / popovers
+ Placeholder examples

**Comment by jv88899** [comment]
What if you said "Length of Time Available for Pairing (example: 03:00 = 3hrs)"?

Or, you could do "Length of Time Available for Pairing" and then have them choose from a dropdown menu that offered hours/minutes using 15 minute increments?

**Comment by tdreid** [comment]
Similar @jv88899 's suggestion a slider could clarify as well as put the entry in the ideal format.

Longer term would you want to capture a schedule and time zone instead of raw hours available?

**Comment by jv88899** [comment]
@tdreid I was thinking along those same lines as well. You could have an input for available start time and an input for available end time and then have them choose a timezone.

**Comment by JacksonBates** [comment]
> You could have an input for available start time and an input for available end time and then have them choose a timezone.

This introduces unnecessary complications I think - As soon as people start having to work out the timezone differences for themselves, it'll start putting people off.

Longer term some sort of scheduling tool might be good - but we'll get authentication and internal messaging off the ground first.

 > "Length of Time Available for Pairing (example: 03:00 = 3hrs)"

I like this language suggestion. That could be implemented straight away if you want to do it.

> a slider could clarify as well as put the entry in the ideal format.

A slider could be good - we should think about the possible trade-offs between the accessibility implications and the improved data validation we get from a slider. 
+ Any thoughts about the slider as a UI component in general? 
+ Can it be controlled with the keyboard? 
+ Can it be set to increment in 15 min blocks like the dropdown suggestion above?

If someone wants to test those ideas out and report back, we can decide how to move forward on that one.

**Comment by jv88899** [comment]
I can take the task of changing the language to "Length of Time Available for Pairing (example: 03:00 = 3hrs). I'll work on it tonight (I live in Midwest US, Central Time).

**Comment by JacksonBates** [comment]
:+1:

**Comment by hristijankiko** [comment]
I think we should create a circle with question mark next to the label that shows tooltip when you hover over it. Inside that tooltip we can write explanation as long as we want.

**Comment by JacksonBates** [comment]
That's a good idea @hristijankiko - There's a current PR open for this, so I'll see what changes were suggested there.

If it is still useful to add after that PR is merged we'll add that to the todo list.

**Comment by tdreid** [comment]
> - Can it be controlled with the keyboard?
> - Can it be set to increment in 15 min blocks like the drop down suggestion above?

There are implementations where the answers can be yes and yes. There's discussion of how to approach sliders as a keyboard accessible enhancement in this [ux.stackexchange question](http://ux.stackexchange.com/questions/42522/sliders-and-accessibility-usability-of-sliders-for-users-with-disabilities) and this http://www.html5accessibility.com/ tracks which HTML5 elements have UA support in which browsers (range in this case is well supported in all browsers except IE where it's it's rated "partial")

Anyway, the slider's an enhancement to text data entry. The changes @jv88899 would clarify what's to be entered. And that's what the issue called for.

**Comment by JacksonBates** [comment]
Language has been updated - if anyone wants to try implementing a slider, open a new issue / pull request :)
