### ISSUE TITLE
Fix CSS for contents of user-cards on mobile

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#38]
![](http://i.imgur.com/3y8NUpB.jpg)

The 'user-cards' text can overflow and respond poorly to the current constraints of the CSS. See screenshot. Notice the (AEDT) behind the delete button on card 2...

These should be improved.

**Comment by kevcomedia** [comment]
Can I have a shot tomorrow (now is sleep time)? If somebody else wants to take this, feel free.

**Comment by JacksonBates** [comment]
It's all yours Kev!
