### ISSUE TITLE
Fix CSS for 'user cards' position when below footer on mobile

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#39]
![](http://i.imgur.com/DMy7Qxj.jpg)

On mobile, too many user cards makes it impossible to delete the lowest on screen - the delete button is obscured by the footer bar and cannot be scrolled past.

**Comment by fotonist** [comment]
if no one deal with this I can work on it. How can I get it?

**Comment by JacksonBates** [comment]
Do you just mean how do you claim the issue to work on? Or how do you run the local version to work on it?

**Comment by fotonist** [comment]
Actualy I do not know what is "claim issue" and when starting a project where should I begin first. I think, firstly I may need its local version.
And the other problem which I wrote you on forum page, on github I tried to change FIRST_PR_CLUB.md. That is fine for my local repo but I could not merge it to your upstream repo.

**Comment by JacksonBates** [comment]
You can't merge directly with this repo yourself. You need to open a Pull Request.

Let's work through getting your FIRST_PR_CLUB.md change into the repo first.

**Comment by JacksonBates** [comment]
We will communicate through the forum for this, to keep this thread on topic.

**Comment by fotonist** [comment]
double fixed. Maybe I have to delete scroll-style class . That gave much empty space between footer and ending user card.

**Comment by JacksonBates** [comment]
@fotonist no more work is needed on this. It's fixed
