### ISSUE TITLE
Improve language to describe 'preferred setup'

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#4]
Similar to #3.

![image](https://cloud.githubusercontent.com/assets/4337740/20661654/0fe057ee-b5a4-11e6-91f2-dae088860384.png)

The language used to ask users to describe their preferred set up may be unclear.

The intention of this field is to get users to describe the tools they are best able to use on their system.

E.g. Do they wish to use ScreenHero and Skype, or does TeamViewer and Google Hangouts work better for them? Are they tmux wizards?

Please discuss your proposed language improvements below, and whoever gets assigned can make the appropriate change.

The form can be found on lines 49-72 in the Modal, in App.js in the src folder.

Changes may need to occur elsewhere - please discuss first.

Possible improvements include:

Clearer wording
Tool-tips / popovers
Placeholder examples

**Comment by alichristensen** [comment]
What about instead of "Preferred setup" something like "Preferred Pairing Technology" and then input type="checkbox" with those examples you listed above and maybe a text input for an option not already listed?

**Comment by JacksonBates** [comment]
That sounds like a sensible approach.

Do you wanna try and remix the form a little so it does that?

**Comment by alichristensen** [comment]
I will certainly try! It's getting late here though so if no one else is interested I will work on this first thing tomorrow

**Comment by tdreid** [comment]
The section on remotes in [Wikipedia's Pair Programming article](https://en.wikipedia.org/wiki/Pair_programming#Remote_pair_programming) might be helpful when it comes to choosing terminology.

Mashing up phrases from the article "preferred shared desktop software" or "preferred collaboration software" could get the point across.  I like the above ideas about providing examples in any case.

**Comment by JacksonBates** [comment]
I think since the primary target audience is Campers (well, currently they are the _only_ ones who can use it), we should keep the options simple.

Maybe something like:
**Screen Sharing**
[  ] TeamViewer [  ] ScreenHero
**Voice**
[  ] Skype [  ] GoogleHangouts

**Comment by alichristensen** [comment]
I just submitted a pr with an updated form
