### ISSUE TITLE
Error in camper.js when null or undefined is passed to 'setup'

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#42]
#36 Introduced a bug that can crash the app under certain circumstances.

If a user submits a post with a null or undefined 'setup' value, the react app can't render the page or allow new posts to be added.

@jenovs' codepen api request is the thing currently triggering the problem (don't click this unless you know how to use Postman to clean up after yourself :) ) http://codepen.io/jenovs/pen/pNWLmy?editors=0010 

This should probably be fixed on the backend, but the frontend should handle these empty values to

**Comment by planigan** [comment]
I just tested with not checking a checkbox and not filling in other against the code I submitted to solve #43 and if I'm understanding this issue correctly, #48 resolves this as well.

**Comment by planigan** [comment]
BTW, I didn't mean to imply that there was not still an issue with a lack of validation. Rather, I see no error when submitting empty values.

**Comment by JacksonBates** [comment]
Submitting empty values is ok, but the problem comes when using something like Postman or an Ajax request to post null values.

It's not standard behaviour, and we'll lock down the access origin stuff soon so it won't be an issue, but backend validation would still be a nice safety net.
