### ISSUE TITLE
User card displays 'other' setup options incorrectly

### ISSUE THREAD

**Issue by planigan** [JacksonBates/pair-frontend#43]
I was playing with this on surge. I have wanted to try out zoom.us, so I put that in other. The card that is displayed shows: `z, o, o, m, ., u, s`. No idea why that field would have a split done on it, but that's kinda my suspicion.

**Comment by JacksonBates** [comment]
@alichristensen FYI :)

Thanks @planigan - The code parsing that form input splits the data before spitting it back out, because it's assuming you've used the checkboxes.

We'll get around to fixing it (unless you wanna take a stab at it -- all welcome :) )

**Comment by planigan** [comment]
I am digging through the code now. If I figure it out, I'll take a stab at it.

**Comment by JacksonBates** [comment]
That's the spirit :+1:

**Comment by planigan** [comment]
I've discovered something slightly disturbing and I'm not sure that it should be shared publicly. Is there any other channel set up to communicate about the project that has direct messaging?

BTW, the FCC twitch channel supports DMs I think. In case you don't have a preferred chat channel.

**Comment by JacksonBates** [comment]
PM me on the forum: https://forum.freecodecamp.com/users/jacksonbates
