### ISSUE TITLE
Remove the seconds from the time string on the noticeboard cards

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#5]
When a user successfully adds a card to the noticeboard, the available time is rendered as HH:mm:ss

See:
![image](https://cloud.githubusercontent.com/assets/4337740/20661830/d14c70d4-b5a4-11e6-8678-35d67ec52787.png)

The seconds part is unnecessary, the string only needs to show the remaining HH:mm (leaving the timezone information in tact).

Ideally, this problem can be solved without relying on an external library such as moment.js, but if there is a compelling reason for adding this dependency then please share it.

The time string can be found on lines 7 and 21 in Campers.js in the src folder. The value of `this.props.camper.endTime` which is used to create the state in this component is a time stamp in milliseconds, passed from the backend DB.

**Comment by sunsplat** [comment]
I can work on this!

**Comment by sunsplat** [comment]
I'm confused as to how to implement the app. When I click +Add, it takes me to pairboard.surge.sh. Is there a way I can just have a version on my local machine?

**Comment by sunsplat** [comment]
I've submitted a pull request for this issue to be looked at. Thanks!

**Comment by JacksonBates** [comment]
@sunsplat I opened up collaboration before I really thought about having separate dev and prod environments - so at the moment all the redirects kick you off of localhost and stick you back on the live environment! Sorry for the trouble this causes, I know it's annoying :)

We'll try and improve that aspect of the project (as soon as someone who has a better idea of how to organise the project comes along :wink:)
