### ISSUE TITLE
Make the info modal text more relevant

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#50]
The current info modal text was designed to merely explain the technology stack used and provide a little context for those viewing it after the challenge that inspired it.

It would be better to have clear and purposeful information about what the app is for, who it is for , and how to use it.

It should be much shorter and genuinely informative - not just conversational trivia.

**Comment by JacksonBates** [comment]
Added first-timer label - even if you're not super confident about what to write, you can run some copy by me first and that makes this an easy first PR :)

**Comment by IsaacAbrahamson** [comment]
Checking this out right now.

**Comment by ChrisGrayLDN** [comment]
If no-one else is picking this up then I'm happy to take it up? @JacksonBates @IsaacAbrahamson
