### ISSUE TITLE
Is the round trip to the backend 'Reacty' enough?!

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#6]
## Update
@jenovs has made some great progress with this. The delete button could use the same love as the main 'add' form (i.e. handle the change on the client side without bouncing off the pairboard domain).

## Original question:
Noob React question:

The modal form users use to add their availability to the noticeboard uses the 'post' method. This posts to the backend api at https://enigmatic-dawn-95873.herokuapp.com/api/v1/add. The api handles this and sends a redirect back to the pairboard.surge.sh page. The delete button has a similar approach.

Is this the way you are supposed to do it in React, or should it use Ajax, or a different idiomatic React approach?

Discuss below, suggest fixes or volunteer to fix :)

**Comment by jenovs** [comment]
Page refresh after each change doesn't look Reacty.

Here https://facebook.github.io/react/docs/forms.html is suggested to use controlled components and use separate function to submit form.

I think we could use something like axios to make POST less painful (`XMLHttpRequest` is just too much code).

I tried to implement ajax call, but redirect from backend is screwing me over.

API should send back status [and data]. I think it's time for `api/v2/` :smile:

**Comment by JacksonBates** [comment]
Yeah...I was originally looking into axios, but P1xt's deadline was getting too close!

We can probably make the change to the backend without updating the versioning, since it's just fixing the behaviour.

I have plans for v2! (Mostly auth and internal messaging)

**Comment by jenovs** [comment]
I think redirect in POST `/add` route could be easily replaced with `res.status(200).send()` without any consequences, because page will be refreshed after form submit by default, and then it could be overwritten in js on FE.

I think we can start with that and then we'll see.

**Comment by JacksonBates** [comment]
That'll make local dev easier, too, since it won't force a bounce to pairboard.

**Comment by JacksonBates** [comment]
The propsed PR fix for this issue (#34) doesn't quite fix it, yet.

See: https://github.com/JacksonBates/pair-backend/issues/14

> Currently, once the 'Add' form or the 'Delete' button are submitted, the app redirects to the backend API url and stays there.

> To fix this properly, the React component form used to send the data to the API should not 'follow' the data. It should wait quietly for the response and re-render the appropriate DOM element when it is received.

> We might be entering redux territory, and is a front end issue.

**Comment by jenovs** [comment]
Redux will be overkill. We should start from backend by adding additional routes so we can test and tweak them without breaking the frontend.

**Comment by JacksonBates** [comment]
That's smart thinking.

**Comment by MarcPorciuncula** [comment]
Has anyone started work on making the form controlled? Otherwise I might have a stab at it

**Comment by JacksonBates** [comment]
Thanks, Marc. This is on hold while we figure out some backend issues.

**Comment by jenovs** [comment]
Two new routes were added to backend:
To create a post make a POST request to https://enigmatic-dawn-95873.herokuapp.com/api/v1/posts with JSON data in the body of the request.
Response will be created data in JSON format (same as for GET request).
To delete a post make DELETE request to https://enigmatic-dawn-95873.herokuapp.com/api/v1/posts/id where `id` at the end of the url is id of the post.
Response will be HTTP status code (204 if ok or 40* if error);

Usage examples (made in vanilla JS):
[POST](http://codepen.io/jenovs/pen/zoRJrv?editors=0010)
[DELETE](http://codepen.io/jenovs/pen/LbQJQz?editors=0010)

**Comment by jenovs** [comment]
Created PR with refactored Form (still needs some additional fixes).
Delete button is still up for grabs.

**Comment by JacksonBates** [comment]
@jenovs Just tested your changes locally - it's great.

**Comment by JacksonBates** [comment]
#70 fixes the delete button and closes this big issue!

Go team!
