### ISSUE TITLE
Needs to solve shrinkage of profile photos

### ISSUE THREAD

**Issue by fotonist** [JacksonBates/pair-frontend#61]
![profile_image_size2](https://cloud.githubusercontent.com/assets/20875928/20944117/462d7ce4-bc13-11e6-9874-f301b348a515.JPG)

After chosing all pairing technologies a shrinkage occurs on profile images and the delete button is sliding to left.

**Comment by JacksonBates** [comment]
A little movement is fine (it was intentionally designed that way by @kevcomedia to allow the image to be responsive), but I think a minimum scale size that is still reasonable is a good idea.

**Comment by kevcomedia** [comment]
I should have added `min-width` and `min-height`.

I could probably fix this, but I'm thinking of letting others do so.

**Comment by JacksonBates** [comment]
@kevcomedia yeah, leaving the low hanging fruit for newbies is my thinking too :)

**Comment by fotonist** [comment]
fixed it :)
