### ISSUE TITLE
Unlimited data can be entered in textboxes

### ISSUE THREAD

**Issue by fotonist** [JacksonBates/pair-frontend#62]
Textbox data need to be limited
![profile_image_size2](https://cloud.githubusercontent.com/assets/20875928/20944168/752778c4-bc13-11e6-8615-d01d7db04d9d.JPG)

**Comment by varunbabu008** [comment]
How many characters are we looking for here ?

**Comment by JacksonBates** [comment]
I'm not sure - maybe do some tests on mobile and desktop and take some screenshots. I think we want to communicate the basic idea of what people are interested pair programming with maybe a maximum of 4-5 words... maybe less?

**Comment by varunbabu008** [comment]
Just tested the app on Desktop. Contrary to what you see on the post by @fotonist (which I think was tested on mobile), in desktop the text doesn't wrap around. It goes out of screen area. Image attached
<img width="1279" alt="screen shot 2016-12-07 at 17 31 25" src="https://cloud.githubusercontent.com/assets/16211277/20967086/87806e82-bca3-11e6-8268-3bf1af344178.png">
