### ISSUE TITLE
User-cards are added incorrectly

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#64]
On a desktop sized screen, cards should be presented in two columns and new cards are added from left to right.

Currently they do not do this:

![image](https://cloud.githubusercontent.com/assets/4337740/20947728/ab19bc3e-bc64-11e6-8f53-35a3c5aed52e.png)

**Comment by zsoltime** [comment]
Oops, I think it was me. Fixing it right now :)

**Comment by JacksonBates** [comment]
:laughing: I was gonna blame @kevcomedia

**Comment by zsoltime** [comment]
No, it was my fault, however, it's fixed now.  :D
