### ISSUE TITLE
Update local config

### ISSUE THREAD

**Issue by jenovs** [JacksonBates/pair-frontend#72]
Frontend:
- [x] move server back to root;
- [x] uncomment `localhost` in `config.js`;
- [x] uncomment `res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE');` in `server.js`.

~~Backend:~~
~~change port in backend `config_template.json` to `3001` (change it also locally in gitignored `config.json`);~~
~~lock down the backend server.~~

**Comment by JacksonBates** [comment]
'change port in backend' is being dealt with here: https://github.com/JacksonBates/pair-backend/issues/32

@NathanGell has claimed it :)

**Comment by JacksonBates** [comment]
'lock down the backend server.' is an open issue here: https://github.com/JacksonBates/pair-backend/issues/37

@Kornil has an open PR addressing this. It will be merged as soon as the ports are changed too.
