### ISSUE TITLE
Integrate continuous polling for DB data (Wish list!)

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#75]
Possibly a way to solve #74 

The app could quietly keep track of activity in the database and update the page in real time (or close enough to it).

So a user with the app open on their screen can see other users adding of deleting posts without the need to refresh.

**Comment by planigan** [comment]
This sounds like a use case for Websockets. The front end needs to connect to the backend and listen for events. The backend needs to emit a delete event to all connected clients when a card is deleted. 

Of course, polling would work also, but it would obviously be less efficient.

**Comment by jenovs** [comment]
Sockets is the last chapter in Udemy's backend course I'm taking. Haven't watched it yet though. I postponed it for "later when I need it". I may need it now 😊 
Anyway, when I finish my Voting app I'll look into it if no one will.

**Comment by JacksonBates** [comment]
Sockets was my guess too.

I actually just stopped the Stock Chart App to work on pairboard instead a couple of weeks ago and didn't learn socket.io like I was supposed to. Seems like fate has brought us to that point anyway :)

**Comment by varunbabu008** [comment]
@jenovs Was wondering which backend course are you taking ? Was thinking of doing a backend course to get a good grasp. Looks like there is plenty out there

**Comment by jenovs** [comment]
@varunbabu008 https://www.udemy.com/the-complete-nodejs-developer-course-2/
I got it on sale for 11EUR, but you can easily find a coupon online with 97% off.

**Comment by JacksonBates** [comment]
I'm gonna fiddle with this one for a bit
