### ISSUE TITLE
Can not create new user card

### ISSUE THREAD

**Issue by fotonist** [JacksonBates/pair-frontend#79]
I tried to create new user card but the noticeboard page seems empty on localhost??

**Comment by jenovs** [comment]
Works for me. Did you start the server?
If not, open another terminal window and type `node server/server.js`, it should show `Server started on port 3001...`

**Comment by fotonist** [comment]
Yes I started on 3000.` node server/server.js ` started but  page shows` Cannot GET / `

**Comment by jenovs** [comment]
No. You should open two terminal windows. In one you type `node server/server.js` which will start local server with some fake data (on port 3001), and then you type in second window `npm start` which will start React app and open it in browser (on port 3000).

**Comment by fotonist** [comment]
I see. It is ok now. Thank you @jenovs 👍

**Comment by jenovs** [comment]
Also, open `server/server.js` file, find this line:
`// res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE');`
and uncomment it. Then start the server again.
