### ISSUE TITLE
Improve the favicon

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-frontend#8]
Currently the app uses the React favicon.

Let's change that! We have no logo to speak of, so share your ideas below. We should make the favicon for all devices, too.

**Comment by BenGitter** [comment]
It seems like this [site](http://realfavicongenerator.net/) makes it easy to get it to work on all devices.

**Comment by JacksonBates** [comment]
Yeah, I was thinking http://www.favicomatic.com/ :) but same idea.

We need a favicon first, though...at the moment it's just the standard React one.

I've put out the feelers for someone to design one, so we'll see if we get any takers.
