### ISSUE TITLE
400 (Bad Request) trying to add card with "new" account?

### ISSUE THREAD

**Issue by Chovin** [JacksonBates/pair-frontend#86]
I tried to add a card using my forum account.
It gave me a 400 in the console.
I've never made a post with the account but it is definitely on there.
```
enigmatic-dawn-95873.herokuapp.com/api/v1/posts:1 POST https://enigmatic-dawn-95873.herokuapp.com/api/v1/posts 400 (Bad Request)
App.js:125 Error: Request failed with status code 400
    at e.exports (http://pairboard.surge.sh/static/js/main.183da825.js:3:30962)
    at e.exports (http://pairboard.surge.sh/static/js/main.183da825.js:6:17222)
    at XMLHttpRequest.d.(anonymous function) (http://pairboard.surge.sh/static/js/main.183da825.js:3:29719)
```

**Comment by JacksonBates** [comment]
It works for me.

![image](https://cloud.githubusercontent.com/assets/4337740/21084689/6f8f0976-c05b-11e6-9876-a2b15338df27.png)

Can you provide more details? Were you doing this on a local server or the live app? What exactly did you enter for each of the form fields?

**Comment by JacksonBates** [comment]
The age of the user account is a red-herring, since we don't do any checking - we just assume the user exists if you say it does. (Obviously the links and images won't work in those cases though)

**Comment by Chovin** [comment]
Hmm.. Seems to be working.
I was probably getting caught by #87 
This time I chose a default pairing and it worked.

![image](https://cloud.githubusercontent.com/assets/17536161/21084742/162b059e-c054-11e6-9545-79c52465f4c6.png)

![image](https://cloud.githubusercontent.com/assets/17536161/21084749/2628ebfa-c054-11e6-9bb6-e0f6b7abe474.png)

![image](https://cloud.githubusercontent.com/assets/17536161/21084768/3bd8e82e-c054-11e6-8368-3eb3f44bbd06.png)

**Comment by Chovin** [comment]
closing :+1:
