### ISSUE TITLE
Did server port change?

### ISSUE THREAD

**Issue by fotonist** [JacksonBates/pair-frontend#90]
I can not create user cards at localhost:3000

**Comment by JacksonBates** [comment]
Yes, sorry. We changed the mock backend server to 3001 so it didn't conflict with the React dev server

**Comment by fotonist** [comment]
how can  I connect?

**Comment by JacksonBates** [comment]
You only need to run `node server/server` in one terminal window and then `npm start` in the other.

Your Pull Request isn't necessary (and introduces a bug - I couldn't run `node server/server` in you version), so I'll close it.

Let me know if you need more help getting it running.

**Comment by fotonist** [comment]
Yes, `@jenovs` told me before and it worked but now I am trying same things but getting error message.
![capture](https://cloud.githubusercontent.com/assets/20875928/21177988/832ebfa4-c1fe-11e6-9370-1fb495da7ea3.JPG)

**Comment by jenovs** [comment]
Look into `server.js` file, it seems that something there is messed up.
Do `fetch` from source and update your local copy (see `CONTRIBUTING.md`);
https://github.com/JacksonBates/pair-frontend/blob/master/CONTRIBUTING.md#how-to-sync-your-local-repo-with-the-original-repo
